apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: lb
  namespace: metallb-system
spec:
  addresses:
  - 172.18.220.200-172.18.220.250
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: empty
  namespace: metallb-system